services:
  download-site:
    image: nginx:1.27-alpine
    container_name: dwargonmc-download-site
    restart: unless-stopped
    ports:
      - "8081:80"
    volumes:
      - ./:/usr/share/nginx/html:ro
