services:
  admin-site:
    image: nginx:1.27-alpine
    container_name: dwargonmc-admin-site
    restart: unless-stopped
    ports:
      - "8082:80"
    volumes:
      - ./:/usr/share/nginx/html:ro
